### ISSUE TITLE
Automatic Github Releases

### ISSUE THREAD

**Issue by ThomasGesseyJones** [handley-lab/anesthetic#290]
The repository's [build](https://github.com/handley-lab/anesthetic/blob/master/.github/workflows/build.yaml) workflow currently automatically tags and publishes the latest code version to PyPi on a PR being merged to master. For consistency, and the ease of those installing directly from GitHub, it would be good to also automatically produce a GitHub release at the same time.

This has been recently successfully implemented in [globalemu](https://github.com/htjb/globalemu/blob/master/.github/workflows/tag_and_release.yaml) and [ErrorAffirmations](https://github.com/ThomasGesseyJones/ErrorAffirmations/blob/main/.github/workflows/tag_and_release.yaml), using the release-action created by ncipollo. So adding it to the [build](https://github.com/handley-lab/anesthetic/blob/master/.github/workflows/build.yaml) workflow should be a simple case of copying over and modifying the relevant portion of the workflow from those repositories
```yaml
- name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: "${{  steps.tag-version.outputs.tag_version }}"
          tag: "v${{ steps.tag-version.outputs.tag_version }}"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
```
